#! /bin/sh

# AUTOSTART PROGRAMS

pgrep -x sxhkd > /dev/null || sxhkd &
polybar &
# todo: widgets
picom --experimental-backends  --config ~/.config/picom/picom.conf &
~/.fehbg &

# WINDOWS

bspc monitor -d 1 2 3 4 5 6 7 8 9

# CONFIGURATION

bspc config window_gap           12
bspc config border_width         2
bspc config focused_border_color \#f5c2e7
bspc config normal_border_color  \#94e2d5

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# MISC

xsetroot -cursor_name left_ptr &
